import image1 from "../images/necklace2.jpg";
import image2 from "../images/necklace1.jpg";
import image3 from "../images/pics_small1.jpg";
import image4 from "../images/pics_small1bottom.jpg";
import image5 from "../images/pics_small2.jpg";
import image6 from "../images/pics_small2bottom.jpg";

export const necklaceProductList = [
  {
    id: 1,
    type: "necklaces",
    firstImage: image1,
    secondImage: image2,
    images: [image1, image2, image3, image4],
    link: "organicnecklaceproduct",
    price: 200,
    name: "Floflo",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 2,
    type: "necklaces",
    firstImage: image4,
    secondImage: image3,
    link: "organicnecklaceitem2",
    images: [image2, image3, image3, image4],
    price: 220,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 3,
    type: "necklaces",
    firstImage: image6,
    secondImage: image5,
    link: "organicnecklaceitem3",
    images: [image3, image2, image1, image4],
    price: 400,
    name: "Cristal Wave",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    type: "necklaces",
    firstImage: image2,
    secondImage: image1,
    images: [image1, image2, image3, image4],
    link: "organicnecklaceitem4",
    price: 330,
    name: "Spring",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    type: "necklaces",
    firstImage: image6,
    secondImage: image5,
    images: [image1, image2, image3, image4],
    link: "organicnecklaceitem5",
    price: 440,
    name: "Poppy seed",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    type: "necklaces",
    firstImage: image4,
    secondImage: image3,
    images: [image1, image2, image3, image4],
    link: "organicnecklaceitem6",
    price: 520,
    name: "Peach",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: 0,
    total: 0,
  },
];
