import React from "react";

import image1 from "../images/cute2.jpg";
import image2 from "../images/cute3.jpg";
import image3 from "../images/cute4.jpg";
import image4 from "../images/earingwithpearl.jpg";

export const ringsProductList = [
  {
    id: 7,
    type: "rings",
    firstImage: image1,
    secondImage: image2,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organicringitem2",
    price: 20,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
  {
    id: 8,
    type: "rings",
    firstImage: image4,
    secondImage: image3,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organiringitem2",
    price: 30,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
  {
    id: 9,
    type: "rings",
    firstImage: image2,
    secondImage: image1,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organiringitem2",
    price: 3454,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
  {
    id: 10,
    type: "rings",
    firstImage: image4,
    secondImage: image3,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organicringitem2",
    price: 9576,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
  {
    id: 11,
    type: "rings",
    firstImage: image2,
    secondImage: image1,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organicringitem2",
    price: 900,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
  {
    id: 12,
    type: "rings",
    firstImage: image4,
    secondImage: image3,
    images: [image1, image2, image3, image4],
    selectedMaterial: { gold: 0, silver: 22, bronze: 340444 },
    link: "organicringitem2",
    price: 500,
    name: "Liliom",
    info: "sofrfjgklfgjflef",
    inCart: false,
    count: { gold: 0, silver: 0, bronze: 0 },
    total: { gold: 0, silver: 0, bronze: 0 },
  },
];
